# Generated by Django 4.0.1 on 2022-02-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('isbn', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('emailaddress', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('DOB', models.TextField(blank=True, max_length=100, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('mothersname', models.CharField(blank=True, max_length=100, null=True)),
                ('fathersname', models.CharField(blank=True, max_length=100, null=True)),
                ('fatheroccupation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
