# Generated by Django 4.0.1 on 2022-02-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookinv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(blank=True, null=True)),
                ('Author', models.TextField(blank=True, null=True)),
                ('ISBN', models.TextField(blank=True, null=True)),
                ('Publisher', models.TextField(blank=True, null=True)),
                ('Year', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
