# Generated by Django 4.0.1 on 2022-02-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_bookinv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinv',
            name='Year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
