# Generated by Django 4.0.1 on 2022-02-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_year_bookinv_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addbook', models.TextField(blank=True, null=True)),
                ('issuebook', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
