# Generated by Django 4.0.1 on 2022-02-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_ind'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ind',
            new_name='index',
        ),
    ]
