# Generated by Django 4.0.1 on 2022-02-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rename_discription_weather_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='coordinate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
